#!/bin/bash

sudo pacman -Syyu
sudo pacman -S stow
xdg-user-dirs-update
reload-links
install-yay
install-packages

sudo pacman -Syyu
cd ~/dotfiles/dwm/
sudo make clean install
cd ~/dotfiles/st
sudo make clean install
cd -
