#!/bin/bash

if ! echo $PATH | grep -q "$HOME/scripts/" && [ -d "$HOME/scripts/" ]; then
    export PATH=$PATH:$HOME/scripts/
fi

alias ls='eza -a'
alias ll='eza -al'
alias cdot='nvim ~/dotfiles/'
alias smci='sudo make clean install'
alias c='clear'
alias v='nvim .'
alias pac='sudo pacman -S'
