#!/bin/bash

cat ~/dotfiles/config/install/packages | xargs sudo pacman --needed --noconfirm -S
cat ~/dotfiles/config/install/fonts | xargs sudo pacman --needed --noconfirm -S
cat ~/dotfiles/config/install/drivers | xargs sudo pacman --needed --noconfirm -S
cat ~/dotfiles/config/install/yay | xargs yay --needed --noconfirm -S
